---
title: "Visão do gestor"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
#rm(list = ls())
#Lib q será futuramente usada pros painéis interativos
#library(shiny)
#Lib pra conexão com o banco
library(odbc)
#Libs pra trabalhar com a base (cortes e funções similares ao SQL)
library(dplyr)
#library(dbplyr)
library(tidyverse)
#Lib pro gráfico
library(ggplot2)
#lib pros gráficos mais "interativos"
library(plotly)
library(highcharter)
#library(htmlwidgets)
#Lib pra usar paletas de cores
library(RColorBrewer)
#library(viridis)
#Lib usada pros treemaps
#library(treemap)
#Lib usada pros waffles
#library(waffle)
#usada para converter números em moeda
library(scales)

####Variavel de teste para não remover e imprimir valores de teste, 1 para teste, 0 para não estou testando, rodando
teste = F
####Variável usada para não plotar os gráficos na dash
dash = T

##Variável "Global"
##Variável "Global"
empresa = 16 #Super
#empresa = 78 #Komatsu
ano_atual = '2020-01-01' #Para comparação dos campos

##Alterar o nome completo pra primeiro nome mais iniciais dos sobrenomes
func_nome <- function (nome_comp)
{
  lista <- str_split_fixed(nome_comp, " ", 4)
  lista <- lista[, -4]
  lista[,3] = str_sub(lista[,3], 1, 1)
  lista[,2] = str_sub(lista[,2], 1, 1)
  lista[,2] = paste(lista[,2], '.', sep='')
  lista[,3] = paste(lista[,3], '.', sep='')
  lista[,2] <- gsub('^.$', '',lista[,2])
  lista[,3] <- gsub('^.$', '',lista[,3])
  lista[,1] <- paste(lista[,1], lista[,2], lista[,3], sep=' ')
  return (lista[,1])
}

##Alterar o número apresentado na forma americana (com vírgula) para a forma brasileira (com ponto), através da transformação em string
func_fmt_numbr <- function(inteiro)
{
  inteiro_br <- paste("", format(inteiro, decimal.mark = ",", big.mark = ".", nsmall = 2))
  return(inteiro_br)
}

con <- DBI::dbConnect(odbc::odbc(),
                      Driver = 'SQL Server',
                      Server = 'localhost\\SQLEXPRESS01',
                      Database = 'nhmobile_agriculture',
                      Trusted_Connection = 'True')

##Collect cria o df resultado da query, nesse caso, visitas_cliente
visita_cliente <- tbl(con,'visita_cliente') %>%
  select (vc_id, vc_vendedor_id, vc_cliente_id, vc_status_id, vc_resultado_id, vc_data_cadastro) %>%
  filter (vc_data_cadastro >= ano_atual) %>%
  collect ()
##Pra pegar o nome do resultado
visita_resultado <- tbl(con, "visita_resultado") %>%
  select(vr_id, vr_nome, vr_ativo) %>%
  #filter(vre_ativo == 1) %>% ##Ja sao todos ativos
  rename (resultado = vr_nome) %>%
  collect()
##Pra filtrar os resultados da empresa
visita_resultado_empresa <- tbl(con, "visita_resultado_empresa") %>%
  select(vre_resultado_id, vre_empresa_id, vre_ativo) %>%
  filter(vre_ativo == 1, vre_empresa_id == empresa) %>% ##Ja sao todos ativos mas mantive pra manter o filtro, ja filtro a empresa 
  collect()
#Arrumando encoding
Encoding(visita_resultado$resultado) <- 'latin1'

##junta as duas tabelas (resultado e resultado_empresa) pra pegar o id da empresa (vre_empresa_id) e o nome do resultado (vr_nome)
vis_res_emp <- inner_join(visita_resultado, visita_resultado_empresa, by = c('vr_id'= 'vre_resultado_id'))

##Pra pegar o nome do status
visita_status <- tbl(con,'visita_status') %>%
  select(vs_id, vs_nome, vs_ativo) %>%
  filter(vs_ativo == 1) %>%
  rename (motivo = vs_nome) %>%
  collect()
##Pra filtrar os status da empresa
visita_status_empresa <- tbl(con, "visita_status_empresa") %>%
  select(vse_status_id, vse_empresa_id, vse_ativo) %>%
  filter(vse_ativo == 1, vse_empresa_id == empresa) %>%
  collect()
#Arrumando encoding
Encoding(visita_status$motivo) <- 'latin1'

##coleta todos os vendedores
vendedor <- tbl(con, "vendedor") %>%
  select(vendedor_id, vendedor_nome, vendedor_id, vendedor_empresa_id, vendedor_ativo) %>%
  filter(vendedor_ativo == 1, vendedor_empresa_id == empresa) %>%
  collect()
#Arrumando encoding
Encoding(vendedor$vendedor_nome) <- 'latin1'
vendedor$vendedor_nome <- func_nome(vendedor$vendedor_nome)

if(empresa == 16){
  vendedor$vendedor_nome[vendedor$vendedor_id == 723] <- "BRUNO PE.";
  vendedor$vendedor_nome[vendedor$vendedor_id == 812] <- "BRUNO PO.";
  vendedor$vendedor_nome[vendedor$vendedor_id == 942] <- "LUCAS V. I.";
}


##junta as duas tabelas (status e status_empresa) pra pegar o id da empresa (vs_empresa_id) e o nome do status (vs_nome)
vis_st_emp <- inner_join(visita_status, visita_status_empresa, by = c('vs_id'= 'vse_status_id'))

##Juntando visita_cliente com os resultados
vc_ij_vre <- inner_join(visita_cliente, vis_res_emp, by = c('vc_resultado_id' = 'vr_id')) %>%
  select (vc_id, vc_vendedor_id, vc_resultado_id, resultado)
##Juntando visita_cliente com os motivos (status)
vc_ij_vse <- inner_join(visita_cliente, vis_st_emp, by = c('vc_status_id' = 'vs_id'))%>%
  select (vc_id, vc_vendedor_id, vc_status_id, motivo)

##juntando com vendedor pra separar por vendedor
vc_ij_vse_ij_v <- inner_join(vc_ij_vse, vendedor, by = c('vc_vendedor_id' = 'vendedor_id')) %>%
  select (vc_id, vc_vendedor_id, vendedor_nome, vc_status_id, motivo)

##juntando com vendedor pra separar por vendedor
vc_ij_vre_ij_v <- inner_join(vc_ij_vre, vendedor, by = c('vc_vendedor_id' = 'vendedor_id')) %>%
  select (vc_id, vc_vendedor_id, vendedor_nome, vc_resultado_id, resultado)

##Agrupando por vendedor e por motivo (vc_status_id, depois mostrar so motivo)
vc_ij_vse_ij_v <- vc_ij_vse_ij_v %>%
  group_by(vc_vendedor_id, vc_status_id) %>%
  mutate(motivo_n = n()) %>%
  distinct(vc_vendedor_id, .keep_all = T)
  
### Gráfico v0 - Motivo das visitas (status) por vendedor em 2020

##descobrindo numero de status diferentes para criar paleta de cores
n_m_color <- n_distinct(vc_ij_vse_ij_v$vc_status_id)
brbg_mot <- brewer.pal(n_m_color,'BrBG')
axis_h <- list(
  title = ""
)
v0 <- plot_ly(vc_ij_vse_ij_v, type = "bar", x = ~vendedor_nome, y = ~motivo_n,# colors = ~I(motivo),
              colors = brbg_mot,
              name = ~motivo)

v0 <- v0 %>%
  layout(barmode = 'stack',
         xaxis = list(title = '', tickangle = 30, tickfont = list(size = 11)),
         yaxis = list(title = ''))
if(dash == F){
  v0
}


##Agrupando por vendedor e por resultado (vc_status_id, depois mostrar so motivo)
vc_ij_vre_ij_v <- vc_ij_vre_ij_v %>%
  group_by(vc_vendedor_id, vc_resultado_id) %>%
  mutate(resultado_n = n()) %>%
  distinct(vc_vendedor_id, .keep_all = T)

### Gráfico v1 - Resultado das visitas (resultados) por vendedor em 2020
##descobrindo numero de status diferentes para criar paleta de cores
n_r_color <- n_distinct(vc_ij_vre_ij_v$vc_resultado_id)
brbg_res <- brewer.pal(n_r_color,'BrBG')

v1 <- plot_ly(vc_ij_vre_ij_v, type = "bar", x = ~vendedor_nome, y = ~resultado_n,# colors = ~I(motivo),
              colors = brbg_res,
              name = ~resultado)
#marker = list(color = 'lightblue'))
#text = ~paste(categoria_nome,'<br>' , func_fmt_din(fat_med)),
#hoverinfo = "text")
#v0 <- v0 %>%
#  add_trace (y = y = ~motivo_n)

v1 <- v1 %>%
  layout(barmode = 'stack',
         xaxis = list(title = '', tickangle = 30, tickfont = list(size = 11)),
         yaxis = list(title = ''))
if(dash == F){
  v1
}

if(teste == F){
  #tabelas
  rm(visita_resultado_empresa, vis_res_emp, vc_ij_vre, vc_ij_vse, ##vis_st_emp, ##vou usar a vis_st_emp para uma junção (saber qual empresa são feitas as visitas)
     vc_ij_vse_ij_v, vc_ij_vre_ij_v, visita_resultado, visita_status, visita_status_empresa,
     axis_h);
  #variáveis
  rm(brbg_mot, brbg_res, n_r_color, n_m_color);
}

################################################################################################
################################################################################################
### Tabelas e graficos de Clientes

cliente <- tbl(con,'cliente') %>%
  select (cliente_id, cliente_vendedor_id, cliente_empresa_id, cliente_data_cadastro, cliente_cidade, cliente_ultima_visita) %>%
  filter(cliente_empresa_id == empresa) %>%
  collect()

##Clientes cadastrados por vendedor ate 2020
cli_p_v <- cliente %>%
  filter(cliente_data_cadastro < ano_atual) %>%
  group_by(cliente_vendedor_id) %>%
  mutate(n_clientes = n()) %>%
  distinct(cliente_vendedor_id, .keep_all = T) %>%
  select(cliente_vendedor_id, n_clientes) %>%
  ungroup() %>%
  arrange(cliente_vendedor_id)

##Juncao pra pegar nome do vendedor
#cli_p_v <- inner_join(cli_p_v, vendedor, by = c('cliente_vendedor_id' = 'vendedor_id')) %>%
#  select(cliente_vendedor_id, vendedor_nome, n_clientes) %>%
#  arrange(cliente_vendedor_id)

##Clientes cadastrados em 2020 por vendedor
cliente_2020 <- cliente %>%
  filter(cliente_data_cadastro >= ano_atual)

cli_p_v_2020 <- cliente_2020 %>%
  group_by(cliente_vendedor_id) %>%
  mutate(n_clientes_2020 = n()) %>%
  distinct(cliente_vendedor_id, .keep_all = T) %>%
  select(cliente_vendedor_id, n_clientes_2020) %>%
  ungroup() %>%
  arrange(cliente_vendedor_id)

##Juncao pra pegar nome do vendedor
cli_p_v_2020 <- inner_join(cli_p_v_2020, vendedor, by = c('cliente_vendedor_id' = 'vendedor_id')) %>%
  select(cliente_vendedor_id, vendedor_nome, n_clientes_2020)

##Juntando anos anteriores + 2020 em uma tabela (pro plotly)
cli_p_v_t_2020 <- left_join(cli_p_v_2020, cli_p_v, by = c('cliente_vendedor_id')) %>%
  select (cliente_vendedor_id, vendedor_nome, n_clientes, n_clientes_2020)

### Grafico c0 - Distribuicao de clientes cadastrados por vendedor

c0 <- plot_ly(cli_p_v_t_2020, x = ~vendedor_nome, y= ~n_clientes, type = 'bar',
              name = 'Até 2020')
c0 <- c0 %>%
  add_trace(y= ~n_clientes_2020, name = 'Em 2020')
c0 <- c0 %>%
  layout(barmode = 'grouped',
         xaxis = list(title = '', tickangle = 30, tickfont = list(size = 11)),
         yaxis = list(title = ''))

if(dash == F){
  c0
}

if(teste == F){
  #tabelas
  rm(cli_p_v, cli_p_v_2020, cli_p_v_t_2020);
  #variáveis
  rm();
}
### Gráficos de pizza de clientes com e sem negócio
##Contando número de clientes geral e em 2020
n_clientes <- nrow(cliente)
n_clientes_2020 <- nrow(cliente_2020)

##Contar quantos clientes aparecem em negócio
negocio <- tbl(con, "negocio") %>%
  select(negocio_id, negocio_vendedor_id, negocio_cliente_id, negocio_data_cadastro) %>%
  collect()

cli_ij_ng <- inner_join(cliente, negocio, by=c("cliente_id" = "negocio_cliente_id")) %>%
  select(cliente_id, negocio_id)
cli_2020_ij_ng <- inner_join(cliente_2020, negocio, by=c("cliente_id" = "negocio_cliente_id"))%>%
  select(cliente_id, negocio_id)
##Variáveis usadas
n_cli_cneg <- nrow(cli_ij_ng)
n_cli_cneg_2020 <- nrow(cli_2020_ij_ng)

Clientes <- c("Clientes com negócios", "Clientes sem negócio")

n_total <- c(n_cli_cneg, n_clientes-nrow(cli_ij_ng))
n_total_p <- c(round((n_cli_cneg/n_clientes), 2), round(((n_clientes-n_cli_cneg)/n_clientes), 2))

n_2020 <- c(n_cli_cneg_2020, n_clientes_2020-n_cli_cneg_2020)
n_2020_p <- c(round((n_cli_cneg_2020/n_clientes_2020), 2), round(((n_clientes_2020-n_cli_cneg_2020)/n_clientes_2020), 2))

cli_c_s_ng <- data.frame(Clientes, n_total, n_total_p, n_2020, n_2020_p)


### Grafico c1 - Clientes cadastrados que possuem negocio (pizza)
colors_pie<- c("#32CD32", "#FFA500")
c1 <- plot_ly(cli_c_s_ng, labels = ~Clientes, values = ~n_total, type = 'pie', sort = F,
              text = func_fmt_numbr(n_total),
              texttemplate = "%{text} (%{percent})",
              hovertemplate = paste ("%{label} <br>",
                                     "Equivalente a %{percent}",
                                     "<extra></extra>"),
              marker = list(colors = colors_pie))

if(dash == F){
  c1
}

### Grafico c2 - Clientes cadastrados em 2020 que possuem negocio (pizza)
c2 <- plot_ly(cli_c_s_ng, labels = ~Clientes, values = ~n_2020, type = 'pie', sort = F,
              text = func_fmt_numbr(n_2020),
              texttemplate = "%{text} (%{percent})",
              hovertemplate = paste ("%{label} <br>",
                                     "Equivalente a %{percent}",
                                     "<extra></extra>"),
              marker = list(colors = colors_pie))

if(dash == F){
  c2
}
if(teste == F){
  #tabelas
  rm(cliente_2020, cli_ij_ng, cli_2020_ij_ng, cli_c_s_ng, Clientes, n_total, n_total_p, n_2020, n_2020_p);
  #variáveis
  rm(n_cli_cneg, n_cli_cneg_2020, n_clientes, n_clientes_2020, colors_pie);
}
####################################


###Contar clientes/visitas/negocios cadastrados por mês
####################################

##Já filtrado apenas empresa (variavel global)
clientes_mes <- cliente %>%
  filter (cliente_data_cadastro >= ano_atual) %>%
  mutate (ym = format(cliente_data_cadastro, '%m')) %>%
  group_by (ym) %>%
  summarize(n_cli = n()) %>%
  ungroup ()

##Visita precisa juntar com visita_status ou _resultado () pra obter empresa_id ##poderia ser vendedor, mas a tabela vis_st_emp (status c/ status_empresa) já está pronta
##vis_st_emp já vem filtrada pela empresa (var global)
vc_ij_emp <- inner_join(visita_cliente, vis_st_emp, by = c("vc_status_id" = "vs_id")) %>%
  #select(vc_id, vc_status_id, vc_data_cadastro) ##Sem empresa_id
  select(vc_id, vc_status_id, vc_data_cadastro, vse_empresa_id)

visitas_mes <- vc_ij_emp %>%
  filter (vc_data_cadastro >= ano_atual) %>%
  mutate (ym = format(vc_data_cadastro, '%m')) %>%
  group_by (ym) %>%
  summarize(n_vis = n()) %>%
  ungroup ()

##Negocio precisa juntar com vendedor pra obter empresa_id ##Poderia ser cliente também, mas a tabela vendedor é menor
##vendedor já vem filtrado pela empresa (var global)
ng_ij_emp <- inner_join(negocio, vendedor, by = c("negocio_vendedor_id" = "vendedor_id")) %>%
  #select(negocio_id, negocio_vendedor_id, negocio_data_cadastro)%>% ##Sem empresa_id
  select(negocio_id, negocio_vendedor_id, negocio_data_cadastro, vendedor_empresa_id)

negocios_mes <- ng_ij_emp %>%
  filter (negocio_data_cadastro >= ano_atual) %>%
  mutate (ym = format(negocio_data_cadastro, '%m')) %>%
  group_by (ym) %>%
  summarize(n_neg = n()) %>%
  ungroup ()

##Juntando tudo em um só dataframe
cli_ij_vc_mes <- inner_join(clientes_mes, visitas_mes, by = c("ym"))
cli_ij_vc_ij_ng_mes <- inner_join(cli_ij_vc_mes, negocios_mes, by = c("ym"))

##Criando nomes de colunas
meses = c('Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro')
## alterando pra números pra poder fazer da mesma forma
cli_ij_vc_ij_ng_mes$ym <- as.integer(cli_ij_vc_ij_ng_mes$ym)
cli_ij_vc_ij_ng_mes$ym <- with(cli_ij_vc_ij_ng_mes, cut(ym, breaks = c(0,1,2,3,4,5,6,7,8, 9, 10, 11, 12),
                                                              labels = meses))

### Gráfico c3 - Cadastro de clientes, visitas e negócios no ano de 2020
c3 <- plot_ly(cli_ij_vc_ij_ng_mes, type = 'scatter', mode = 'lines+markers', x = ~ym, y = ~n_cli,
              name = 'Clientes',
              text = ~paste(func_fmt_numbr(n_cli), 'clientes'),
              hoverinfo = "text",
              color = I('blue'))
c3 <- c3 %>%
  add_trace (type = 'scatter', mode = 'lines+markers', y = ~n_vis,
             name = 'Visitas',
             text = ~paste(func_fmt_numbr(n_vis), 'visitas'),
             hoverinfo = "text",
             color = I('#DAA520'))
c3 <- c3 %>%
  add_trace (type = 'scatter', mode = 'lines+markers', y = ~n_neg,
             name = 'Negócios',
             text = ~paste(func_fmt_numbr(n_neg), 'negócios'),
             hoverinfo = "text",
             color = I('green'))
  
c3 <- c3 %>%
layout(xaxis = list(title = ''),
       yaxis = list(title = ''))
if(dash == F){
  c3
}

if(teste == F){
  #tabelas
  rm(cliente, visita_cliente, negocio, vendedor, vis_st_emp, cli_ij_vc_mes, cli_ij_vc_ij_ng_mes);
  #variáveis
  rm();
}

################################################################################################################################
################################################################################################################################


```

Volume de visitas
=======================================================================

Column {data-width=550}
-----------------------------------------------------------------------

### Distribuição dos motivos das visitas por vendedor em 2020

```{r}

### Gráfico v0 - Motivo das visitas (status) por vendedor em 2020
v0

```

Column {data-width=550}
-----------------------------------------------------------------------

### Distribuição de resultado das visitas por vendedor em 2020

```{r}
### Gráfico v1 - Resultado das visitas (resultados) por vendedor em 2020
v1

```


Clientes
=======================================================================

Column {data-width=550}
-----------------------------------------------------------------------

### Distribuição de clientes cadastrados por vendedor

```{r}

### Grafico c0 - Distribuicao de clientes cadastrados por vendedor
c0

```

Column {data-width=550}
-----------------------------------------------------------------------

### Distribuição de clientes com ou sem negócios

```{r}

### Grafico c1 - Clientes cadastrados que possuem negocio (pizza)
c1

```



### Distribuição de clientes cadastrados em 2020 com ou sem negócios

```{r}

### Grafico c2 - Clientes cadastrados em 2020 que possuem negocio (pizza)
c2

```

Cadastros em 2020
=======================================================================

Column {data-width=550}
-----------------------------------------------------------------------

### Cadastro de clientes, visitas e negócios em 2020

```{r}

### Gráfico c3 - Cadastro de clientes, visitas e negócios no ano de 2020
c3

```

