---
title: "Visão do gestor"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
rm(list = ls())
library(flexdashboard)
library(shiny)
library(odbc)
library(dplyr)
library(dbplyr)
library(ggplot2)
library(tidyverse)
library(plotly)

library(RColorBrewer)




con <- DBI::dbConnect(odbc::odbc(), 
                      Driver = "SQL Server", 
                      Server = "localhost\\SQLEXPRESS", 
                      Database = "nhmobile_agriculture", 
                      Trusted_Connection = "True")

negocio <- tbl(con, "negocio") %>%
  select(negocio_id, negocio_vendedor_id, negocio_negocio_situacao_id, negocio_data_cadastro) %>%
  collect()

#coleta todos os vendedores
vendedor_todos <- tbl(con, "vendedor") %>%
  select(vendedor_id, vendedor_nome, vendedor_empresa_id,vendedor_ativo) %>%
  collect()
#filtra os vendedores ativos
#vendedor <- filter(q_vendedor_todos, q_vendedor_todos$vendedor_ativo == 1)

historico_negocio_situacao <- tbl(con, "historico_negocio_situacao") %>%
  select(historico_negocio_situacao_data, historico_negocio_situacao_negocio_id, historico_negocio_situacao_situacao_id) %>%
  collect()

historico_negocio_situacao_2020 <- historico_negocio_situacao %>%
  filter(historico_negocio_situacao_data >= as.Date("2020-01-01 00:00:00"))

#join de negocios e vendedores
negocio_lj_vendedor <- left_join(negocio, vendedor_todos, by=c("negocio_vendedor_id" = "vendedor_id"))
negocio_rj_historico_lj_vendedor <- right_join(negocio_lj_vendedor, historico_negocio_situacao_2020, by=c("negocio_id" = "historico_negocio_situacao_negocio_id"))

negocio_rj_historico_lj_vendedor <- negocio_rj_historico_lj_vendedor[order(-negocio_rj_historico_lj_vendedor$historico_negocio_situacao_situacao_id, negocio_rj_historico_lj_vendedor$negocio_id),]
ng_rj_hist_lj_ven <- negocio_rj_historico_lj_vendedor[!duplicated(negocio_rj_historico_lj_vendedor$negocio_id),]


#verificar se está mesmo ordenado, verifiquei pra um vendedor pra ser mais fácil de visualizar
#negocio_rj_historico_lj_vendedor_x <- negocio_rj_historico_lj_vendedor %>%
#  filter(negocio_rj_historico_lj_vendedor$negocio_vendedor_id == "1085")


#Aqui eu consegui remover e deixar apenas o último estado (testado pelo código 202005181537022911085 que ficou só o mais recente)
#t1 <- negocio_rj_historico_lj_vendedor_x
#t1 <- t1[!duplicated(t1$negocio_id),]

#202005181537022911085 -> negocio_id que teve alteração em 2020, para testes

#verificar duplicidade
#ng_rj_hist_lj_ven$negocio_id[duplicated(ng_rj_hist_lj_ven$negocio_id)]

#removendo elementos não mais usados
rm(negocio, vendedor_todos, historico_negocio_situacao, historico_negocio_situacao_2020, negocio_rj_historico_lj_vendedor)

#corte inicial, selecionando apenas uma empresa, id 16 = Super, vendedor_ativo se o vendedor está ativo (true ou false), data
#Aqui vejo só negócios cadastrados em 2020, preciso ver negócios faturados em 2020

corte_1 <- ng_rj_hist_lj_ven %>%
    filter(vendedor_empresa_id =="16", vendedor_ativo == TRUE, historico_negocio_situacao_data >= as.Date("2020-01-01"), negocio_negocio_situacao_id != 0) %>%
    select(negocio_id, negocio_negocio_situacao_id, negocio_vendedor_id, vendedor_ativo, vendedor_nome, negocio_data_cadastro)


##agrupamento de negocios por vendedor
##Aqui eu poderia fazer um group_by + summarise pra ter apenas coluna id_vendedor + count(negocios) e depois o join, sem o select, ou então usar o mutate como foi feito
ng_lj_vn_2020 <- corte_1 %>%
  select(negocio_id, negocio_vendedor_id, negocio_negocio_situacao_id, vendedor_nome) %>%
  group_by(negocio_negocio_situacao_id, negocio_vendedor_id) %>%
  mutate(num_negocios = n()) %>%
  distinct (negocio_vendedor_id, .keep_all = TRUE) %>%
  collect ()


#removendo elementos não mais usados
rm(corte_1, negocio_lj_vendedor)

#aqui eu estou alterando o joão paulo, que havia problemas com codificação
ng_lj_vn_2020$vendedor_nome[ng_lj_vn_2020$negocio_vendedor_id == 45] <- "JOÃO PAULO"

##remover status "desconsiderar (erro cadastro)"
ng_lj_vn_2020 <- ng_lj_vn_2020[!(ng_lj_vn_2020$negocio_negocio_situacao_id==9),]

##aqui ele transforma os inteiros em chars pra fazermos a alteração
ng_lj_vn_2020$negocio_negocio_situacao_id <- as.character(ng_lj_vn_2020$negocio_negocio_situacao_id)


status = c("1 - em negociacao", "2 - montagem de cadastro", "3 - aguardando aprovacao", "5 - faturado", "4 - financiamento aprovado", "6 - financiamento nao aprovado", "7 - desistencia do cliente", "8 - perdemos para concorrencia", "0 - intencao ou prospeccao")

##aqui ele substitui linha a linha cada situação pelo seu respectivo em string
ng_lj_vn_2020$negocio_negocio_situacao_id[ng_lj_vn_2020$negocio_negocio_situacao_id == "1"] <- status[1]
ng_lj_vn_2020$negocio_negocio_situacao_id[ng_lj_vn_2020$negocio_negocio_situacao_id == "2"] <- status[2]
ng_lj_vn_2020$negocio_negocio_situacao_id[ng_lj_vn_2020$negocio_negocio_situacao_id == "3"] <- status[3]
ng_lj_vn_2020$negocio_negocio_situacao_id[ng_lj_vn_2020$negocio_negocio_situacao_id == "4"] <- status[4]
ng_lj_vn_2020$negocio_negocio_situacao_id[ng_lj_vn_2020$negocio_negocio_situacao_id == "5"] <- status[5]
ng_lj_vn_2020$negocio_negocio_situacao_id[ng_lj_vn_2020$negocio_negocio_situacao_id == "6"] <- status[6]
ng_lj_vn_2020$negocio_negocio_situacao_id[ng_lj_vn_2020$negocio_negocio_situacao_id == "7"] <- status[7]
ng_lj_vn_2020$negocio_negocio_situacao_id[ng_lj_vn_2020$negocio_negocio_situacao_id == "8"] <- status[8]
ng_lj_vn_2020$negocio_negocio_situacao_id[ng_lj_vn_2020$negocio_negocio_situacao_id == "10"] <- status[9]


#tabela vem dessa: ng_rj_hist_lj_ven

ng_rj_hist_lj_ven <- ng_rj_hist_lj_ven %>%
  filter(vendedor_empresa_id =="16", vendedor_ativo == TRUE, historico_negocio_situacao_data >= as.Date("2020-01-01")) %>%
  select(negocio_id, negocio_negocio_situacao_id, negocio_vendedor_id, vendedor_ativo, vendedor_nome, negocio_data_cadastro, historico_negocio_situacao_data)

#aqui eu estou alterando o joão paulo (da super empresa_id 16), que havia problemas com codificação
ng_rj_hist_lj_ven$vendedor_nome[ng_rj_hist_lj_ven$negocio_vendedor_id == 45] <- "JOÃO PAULO"

##remover status "desconsiderar (erro cadastro)"
ng_rj_hist_lj_ven <- ng_rj_hist_lj_ven[!(ng_rj_hist_lj_ven$negocio_negocio_situacao_id==9),]


###Começar a junção dos gráficos
##aqui caso o filtro seja mais de um, usamos o %in% ff
## 4 - faturado, 6 - desistencia do cliente, 7 - perdemos para a concorrencia
ff <- c(4, 6, 7, 8)
#ggplotly(p1)

ng_f_cn_d_vn <-  ng_rj_hist_lj_ven%>%
  filter(negocio_negocio_situacao_id %in% ff)

ng_f_cn_d_vn$negocio_negocio_situacao_id[ng_f_cn_d_vn$negocio_negocio_situacao_id == "4"] <- status[4]
ng_f_cn_d_vn$negocio_negocio_situacao_id[ng_f_cn_d_vn$negocio_negocio_situacao_id == "6"] <- status[6]
ng_f_cn_d_vn$negocio_negocio_situacao_id[ng_f_cn_d_vn$negocio_negocio_situacao_id == "7"] <- status[7]
ng_f_cn_d_vn$negocio_negocio_situacao_id[ng_f_cn_d_vn$negocio_negocio_situacao_id == "8"] <- status[8]

ng_f_cn_d_vn <- ng_f_cn_d_vn %>%
  select(negocio_id, negocio_vendedor_id, negocio_negocio_situacao_id, vendedor_nome) %>%
  group_by(negocio_negocio_situacao_id, negocio_vendedor_id) %>%
  mutate(num_negocios = n()) %>%
  distinct (negocio_vendedor_id, .keep_all = TRUE) %>%
  collect ()
##negocio num de itens (trator e colheitadeira)

negocio_produto <- tbl(con, "negocio_produto") %>%
  select(np_id, np_negocio_id, np_produto_id, np_quantidade,np_ativo, np_valor) %>%
  collect()

##Vou selecionar produto_nome pra não ter q mudar depois, mas posso cortar essa coluna se preciso e ir só por prod_id
produto <- tbl(con, "produto") %>%
  select(produto_id, produto_nome, produto_marca_id, produto_categoria_id, produto_empresa_id) %>%
  collect()

## Inner join pra não pegar os np_produto_id = 0
ngp_lj_pd <- inner_join(negocio_produto, produto, by=c("np_produto_id"="produto_id")) %>%
  select (np_negocio_id, np_produto_id, produto_nome, produto_marca_id, produto_categoria_id, produto_empresa_id, np_quantidade, np_valor, np_ativo)

## Removendo os inativos (np_ativo == 0)
ngp_lj_pd <- ngp_lj_pd[!ngp_lj_pd$np_ativo == 0,]

rm(negocio_produto, produto)

##tabela usada pra termos negócios, data de atualização (hist), nome do vendedor (vend) e produtos (negocio produto e produto)
ng_rj_hist_lj_ven_lj_ngp_lj_pd <- left_join(ng_rj_hist_lj_ven, ngp_lj_pd, by = c("negocio_id" = "np_negocio_id"))

remove(ng_rj_hist_lj_ven, ngp_lj_pd)

##ahhh, antes que eu esqueca é muito importante validar o np_ativo=1 (ativo)

##
##filtrando antes, apenas tratores e colheitadeiras (produto_categoria = 1, 2, 3 e 4, como trator, colheitadeira, pulverizador e plantadeira, respectivamente, demais, recategorizar como "outros")
ng_rj_hist_lj_ven_lj_ngp_lj_pd$produto_categoria_id[ng_rj_hist_lj_ven_lj_ngp_lj_pd$produto_categoria_id != c(1,2,3,4)] <- 5
categoria <- c("Trator", "Colheitadeira", "Pulverizador", "Plantadeira", "Outros")

ng_rj_hist_lj_ven_lj_ngp_lj_pd$produto_categoria_id[ng_rj_hist_lj_ven_lj_ngp_lj_pd$produto_categoria_id == 1] <- categoria[1]
ng_rj_hist_lj_ven_lj_ngp_lj_pd$produto_categoria_id[ng_rj_hist_lj_ven_lj_ngp_lj_pd$produto_categoria_id == 2] <- categoria[2]
ng_rj_hist_lj_ven_lj_ngp_lj_pd$produto_categoria_id[ng_rj_hist_lj_ven_lj_ngp_lj_pd$produto_categoria_id == 3] <- categoria[3]
ng_rj_hist_lj_ven_lj_ngp_lj_pd$produto_categoria_id[ng_rj_hist_lj_ven_lj_ngp_lj_pd$produto_categoria_id == 4] <- categoria[4]
ng_rj_hist_lj_ven_lj_ngp_lj_pd$produto_categoria_id[ng_rj_hist_lj_ven_lj_ngp_lj_pd$produto_categoria_id == 5] <- categoria[5]


##não estou selecionando empresa_id nem np_ativo no momento, nome e marcaremovido já que ele só pega de um deles e estou selecionando categoria
## np_quantidade e valor também removidos já que estou categorizando
ng <- ng_rj_hist_lj_ven_lj_ngp_lj_pd %>%
  select(negocio_id, negocio_vendedor_id, negocio_negocio_situacao_id, vendedor_nome, historico_negocio_situacao_data, produto_categoria_id) %>%
  group_by(produto_categoria_id, negocio_vendedor_id) %>%
  mutate(num_negocios = n()) %>%
  distinct (negocio_vendedor_id, .keep_all = TRUE) %>%
  collect ()


```

Volume de negócios
=======================================================================

Column {data-width=650}
-----------------------------------------------------------------------

### Volume de negócios cadastrados por vendedor, ano 2020

```{r}
##Gráfico do número de clientes por vendedor
p0 <- ggplot(ng_lj_vn_2020, aes(vendedor_nome, num_negocios, fill=factor(negocio_negocio_situacao_id), label = num_negocios)) + #usar o fill pra criar os léveis, ele já ordena por ordem alfabética
  geom_col(position = "stack") +
  ylab("Número de clientes") +
  #ggtitle("Volume de negócios cadastrados por vendedor, ano 2020") +
  theme (axis.text.x = element_text(angle = 30, hjust = 1), axis.title = element_blank())+
  scale_fill_manual(values = c("#ADD8E6", "#87CEEB", "#1E90FF", "#00BFFF", "#87CEFA", "#32CD32", "yellow", "orange", "#DE0D26"),
  )#+
#geom_text(position = position_stack(vjust = +0.5))

##Se usar ggplot vai pro lugar, se usar o plotly tem q mover como fiz abaixo
#p0 <- p0+theme (legend.position = "bottom") -> 
ggplotly(p0) %>%
  layout(legend = list(orientation = "h", x = 0, y = -0.22))


```

Column {data-width=350}
-----------------------------------------------------------------------

### Volume de negócios fechados em 2020

```{r}
p3 <- ggplot(ng_f_cn_d_vn, aes(vendedor_nome, num_negocios, fill=factor(negocio_negocio_situacao_id), label = num_negocios)) + #usar o fill pra criar os léveis, ele já ordena por ordem alfabética
  geom_col(position = "stack") +
  xlab("Vendedores") +
  ylab("Número de clientes") +
  ggtitle("Volume de negócios fechados em 2020") +
  theme (axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_fill_manual(name = "situação do contrato",
                    values = c("#32CD32", "yellow", "orange", "#DE0D26"),
  )+
  coord_flip(expand = F) +
  geom_text(position = position_stack(vjust = +0.5))

ggplotly(p3) %>%
  layout(legend = list( orientation = "h", x = 0, y = -0.2))

```

Negócios por categoria
=======================================================================

### Tipos de máquina em negociação, em 2020

```{r}

p4 <- ggplot(ng, aes(vendedor_nome, num_negocios, fill=factor(produto_categoria_id), label = num_negocios)) + #usar o fill pra criar os léveis, ele já ordena por ordem alfabética
  geom_col(position = "stack") +
  xlab("Vendedores") +
  ylab("Número de produtos") +
  ggtitle("Tipos de máquinas em negociação, em 2020") +
  theme (axis.text.x = element_text(angle = 45, hjust = 1), axis.title = element_blank())+
  scale_fill_brewer(palette = "Dark2")+
  geom_text(position = position_stack(vjust = +0.5))

##Aqui eu estou removendo as legendas criadas pelo fill já que não consegui mudar elas de posição
##Se usar ggplot vai pro lugar, se usar o plotly tem q mover como fiz abaixo
#p0 <- p0+theme (legend.position = "bottom") -> 
ggplotly(p4)
```