---
title: "Visão do gestor"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
params:
  variable1: "emp_par"
---

```{r setup, include=FALSE}
#rm(list = ls())
#Lib q será futuramente usada pros painéis interativos
#library(shiny)
#Lib pra conexão com o banco
#library(odbc)
#Lib para ler (mais rapidamente) os csvs
library(data.table)
#lib com uma cacetada de outras libs para manipular dados
library(tidyverse)
#Libs pra trabalhar com a base (cortes e funções similares ao SQL)
#library(dplyr) #Contido no tidyverse
#Lib pro gráfico
library(ggplot2)
#lib pros gráficos mais "interativos"
library(plotly)
library(highcharter)
#library(htmlwidgets)
#Lib pra usar paletas de cores
library(RColorBrewer)
#library(viridis)
#Lib usada pros treemaps
#library(treemap)
#Lib usada pros waffles
#library(waffle)
#Lib para funções de tempo
library(lubridate)
#usada para converter números em moeda
#library(scales)
#Lib usada para emojis/fonts/box de valores
library(ggplot2)
#Lib usada para os quadros
library(emojifont)



###################################
##Variáveis "Globais"
####Variavel de teste para não remover e imprimir valores de teste, 1 para teste, 0 para não estou testando, rodando
teste = F
####Variável usada para não plotar os gráficos na dash
dash = T
####Variavel global c/ ano atual (para comparação)
ano_atual = ymd(today()) - months(month(today())-1) - days(day(today())-1)

##Variável "Global"
emp_am = 42 # Amazonia
emp_ar = 77 # Araguaia
emp_ko = 78 # Komatsu
emp_ms = 35 # Ms
emp_si = 59 # Simex
emp_su = 16 # Super
emp_ta = 60 # Taisa

#Teste se o parâmetro foi setado ou não
if(params$variable1 == 'emp_par'){
  empresa <- emp_ta
} else{
##Empresa utilizada
  if (params$variable1 == 'Amazonia'){
    empresa = emp_am
  }else{
      if(params$variable1 == 'Araguaia'){
        empresa = emp_ar
      }else{
        if(params$variable1 == 'MS'){
          empresa = emp_ms
        }else{
          if(params$variable1 == 'Simex'){
            empresa = emp_si
          }else{
            if(params$variable1 == 'Taisa'){
              empresa = emp_ta
              }else{
                if (params$variable1 == 'Super'){
                  empresa = emp_su
                } else{
                  if(params$variable1 == 'Komatsu'){
                    empresa = emp_ko
                  }
                }
              }
            }
          }
        }
      }
  }
###################################

##Alterar o valor de inteiro para reais
func_fmt_din <- function(inteiro)
{
  inteiro_em_reais <- paste("R$", format(inteiro, decimal.mark = ",", big.mark = ".", nsmall = 2))
  return(inteiro_em_reais)
}
##Alterar o valor de inteiro para reais convertendo para milhões (78000000 = R$78,0) -> posteriormente adicionar o "mi"
func_fmt_din_mi <- function(inteiro)
{
  inteiro <- round(inteiro/1000000, digits = 1)
  inteiro_mi_em_reais <- paste("R$", format(inteiro, decimal.mark = ",", big.mark = ".", nsmall = 1))
  return(inteiro_mi_em_reais)
}
##Alterar o nome completo pra primeiro nome mais iniciais dos sobrenomes
func_nome <- function (nome_comp)
{
  lista <- str_split_fixed(nome_comp, " ", 4)
  lista <- lista[, -4]
  lista[,3] = str_sub(lista[,3], 1, 1)
  lista[,2] = str_sub(lista[,2], 1, 1)
  lista[,2] = paste(lista[,2], '.', sep='')
  lista[,3] = paste(lista[,3], '.', sep='')
  lista[,2] <- gsub('^.$', '',lista[,2])
  lista[,3] <- gsub('^.$', '',lista[,3])
  lista[,1] <- paste(lista[,1], lista[,2], lista[,3], sep=' ')
  return (lista[,1])
}
##Alterar o número apresentado na forma americana (com vírgula) para a forma brasileira (com ponto), através da transformação em string
func_fmt_numbr <- function(inteiro)
{
  inteiro_br <- paste("", format(inteiro, decimal.mark = ",", big.mark = ".", nsmall = 2))
  return(inteiro_br)
}

###Começando scripts negocio_scripts
###########################################################################################################

##-> Collect cria o dataframe resultado da query, negocio será a tabela na qual estou lendo (FROM cliente)
negocio <- fread("Tabelas/negocio.csv", colClasses = c(negocio_id = "character", negocio_produto_id = "character")) %>%
  select(negocio_id, negocio_vendedor_id, negocio_negocio_situacao_id, negocio_data_cadastro, negocio_usado, negocio_produto_id)


##coleta todos os vendedores
vendedor <- fread("Tabelas/vendedor.csv") %>%
  select(vendedor_id, vendedor_nome, vendedor_empresa_id, vendedor_ativo) %>%
  filter (vendedor_empresa_id == empresa, vendedor_ativo == 1) %>%
  select(-vendedor_ativo)


#Arrumando encoding
Encoding(vendedor$vendedor_nome) <- 'latin1'
vendedor$vendedor_nome <- func_nome(vendedor$vendedor_nome)

if(empresa == 16){
  vendedor$vendedor_nome[vendedor$vendedor_id == 723] <- "BRUNO PE.";
  vendedor$vendedor_nome[vendedor$vendedor_id == 812] <- "BRUNO PO.";
  vendedor$vendedor_nome[vendedor$vendedor_id == 942] <- "LUCAS V. I.";
}

##negocio_produto para pegar os valores de cada negócio
negocio_produto <- fread("Tabelas/negocio_produto.csv", colClasses = c(np_id = "character", np_negocio_id = "character", np_produto_id = "character")) %>%
  select(np_id, np_negocio_id, np_produto_id, np_quantidade,np_ativo, np_valor)


##Vou selecionar produto_nome pra não ter q mudar depois, mas posso cortar essa coluna se preciso e ir só por prod_id
produto <- fread("Tabelas/produto.csv", colClasses = c(produto_id = "character", produto_marca_id = "character", produto_categoria_id = "character")) %>%
  select(produto_id, produto_nome, produto_marca_id, produto_categoria_id, produto_empresa_id)

##join de negocios e vendedores
negocio_ij_vendedor <- inner_join(negocio, vendedor, by=c("negocio_vendedor_id" = "vendedor_id"))

########## Para o funil e para agrupar por faturamento
#### Vou alterar o agrupamento de número de negócios para faturamento, portanto precisarei da tabela negocio_produto
neg_ij_ven_ij_np <- inner_join(negocio_ij_vendedor, negocio_produto, by=c("negocio_id" = "np_negocio_id"))

##Filtrando empresa, vendedores ativos e negocios de anat
neg_ij_ven_ij_np_anat <- neg_ij_ven_ij_np %>%
  filter(negocio_data_cadastro >= ano_atual, negocio_negocio_situacao_id != 0)

##removendo elementos não mais usados
if (teste == F) {
  rm() #vou precisar dele pro funil mais pra baixo negocio_ij_historico_ij_vendedor_anat)
}

##agrupamento de negocios por vendedor, contando faturamento por status e por vendedor
##Aqui eu poderia fazer um group_by + summarise pra ter apenas coluna id_vendedor + count(negocios) e depois o join, sem o select, ou então usar o mutate como foi feito
ng_ij_vn_ij_np_fat <- neg_ij_ven_ij_np_anat %>%
  select(negocio_id, negocio_vendedor_id, negocio_negocio_situacao_id, vendedor_nome, negocio_vendedor_id, np_valor) %>%
  group_by(negocio_negocio_situacao_id, negocio_vendedor_id) %>%
  mutate(total_fat = sum(np_valor)) %>%
  distinct (negocio_vendedor_id, .keep_all = TRUE) %>%
  collect ()

###remover status "desconsiderar (erro cadastro)"
ng_ij_vn_ij_np_fat <- ng_ij_vn_ij_np_fat[!(ng_ij_vn_ij_np_fat$negocio_negocio_situacao_id==9),]

status = c("Em negociação", "Montagem de cadastro", "Aguardando aprovação", "Faturado", "Financiamento não aprovado", "Desistência do cliente",
           "Perdemos para concorrência", "Financiamento aprovado", "Intenção ou prospecção")
##aqui ele substitui linha a linha cada situação pelo seu respectivo em string
ng_ij_vn_ij_np_fat$negocio_status <- with(ng_ij_vn_ij_np_fat, cut(negocio_negocio_situacao_id, breaks = c(0,1,2,3,4,5,6,7,8,10), labels = status))
#precisa usar o factor pra colocar na ordem que quero
ng_ij_vn_ij_np_fat$negocio_status = factor(ng_ij_vn_ij_np_fat$negocio_status, levels = c("Intenção ou prospecção", "Em negociação", "Montagem de cadastro",
                                                                                         "Aguardando aprovação", "Financiamento aprovado", "Faturado", "Financiamento não aprovado",
                                                                                         "Desistência do cliente", "Perdemos para concorrência"))

#usando função pra criar outra coluna com número formatado (em Real, com pontos)
ng_ij_vn_ij_np_fat <- ng_ij_vn_ij_np_fat %>%
  mutate(total_fat_t = func_fmt_din(total_fat))

###Gráfico n0 - Faturamento dos negócios por vendedor (anat, status atual)
##############################################
n0 <- plot_ly(ng_ij_vn_ij_np_fat, type = 'bar', orientation = 'h', x = ~total_fat , y = ~reorder(vendedor_nome, desc(vendedor_nome)),
              color = ~negocio_status,
              colors = c("#ADD8E6", "#87CEEB" , "#87CEFA", "#00BFFF", "#3182FF", "#32CD32", "yellow", "orange", "#DE0D26"),
              name = ~negocio_status,
              showlegend = TRUE
              )

n0 <- n0 %>%
  layout(barmode = 'stack',
         xaxis = list(title = ''),
         yaxis = list(title = ''))

if(dash == F){
  n0
}

##vou manter ng_ij_vn_ij_np_fat pra fazer o join mais pro final
if (teste == F) {
  rm(ng_ij_vn_ij_np_fat, status)
}
##############################################
##Faturamento de negócios fechados em anat
historico_negocio_situacao <- fread("Tabelas/historico_negocio_situacao.csv", colClasses = c(historico_negocio_situacao_situacao_id = "character")) %>%
  select(historico_negocio_situacao_data, historico_negocio_situacao_negocio_id, historico_negocio_situacao_situacao_id)

historico_negocio_situacao_anat <- historico_negocio_situacao %>%
  filter(historico_negocio_situacao_data >= ano_atual)

##Right join de negocios, vendedores com histórico pra ter apenas a última
negocio_ij_historico_ij_vendedor_anat <- inner_join(negocio_ij_vendedor, historico_negocio_situacao_anat, by=c("negocio_id" = "historico_negocio_situacao_negocio_id"))
negocio_ij_historico_ij_vendedor_total <- inner_join(negocio_ij_vendedor, historico_negocio_situacao, by=c("negocio_id" = "historico_negocio_situacao_negocio_id"))

##aqui estou ordenando por historico_negocio_situacao_situacao_id pra depois remover as atualizações mais antigas, ficar só com a última atualização no negócio
negocio_ij_historico_ij_vendedor_anat <- negocio_ij_historico_ij_vendedor_anat[order(-negocio_ij_historico_ij_vendedor_anat$historico_negocio_situacao_situacao_id, negocio_ij_historico_ij_vendedor_anat$negocio_id),]
ng_ij_hist_ij_ven_anat <- negocio_ij_historico_ij_vendedor_anat[!duplicated(negocio_ij_historico_ij_vendedor_anat$negocio_id),]


##tabela vem dessa: ng_ij_hist_ij_ven_anat, já foi filtrada para histórico anat, filtrando empresa_id, vendedor_ativo
ng_ij_hist_ij_ven_anat <- ng_ij_hist_ij_ven_anat %>%
  filter(vendedor_empresa_id == empresa) %>%
  select(negocio_id, negocio_negocio_situacao_id, negocio_vendedor_id, vendedor_nome, negocio_data_cadastro, historico_negocio_situacao_data)

##filtrando dois negócios que tem seu status 0 (possivel erro)
ng_ij_hist_ij_ven_anat <- ng_ij_hist_ij_ven_anat %>%
  filter(negocio_negocio_situacao_id != 0)

####Aqui é pra testar um top10 de uma empresa específica
##ng_ij_hist_ij_ven_top10 <-ng_ij_hist_ij_ven_anat

ng_ij_hist_ij_ven_ij_np_anat <- inner_join(ng_ij_hist_ij_ven_anat, negocio_produto, by=c("negocio_id" = "np_negocio_id"))

ff <- c(4, 5, 6, 7)

ng_ij_hist_ij_ven_anat_ij_np_fec <-  ng_ij_hist_ij_ven_ij_np_anat%>%
  filter(negocio_negocio_situacao_id %in% ff)

ng_ij_hist_ij_ven_anat_ij_np_fec <- ng_ij_hist_ij_ven_anat_ij_np_fec %>%
  mutate(negocio_status = negocio_negocio_situacao_id)


status_4_5_6_7 = c("Faturado", "Financiamento não aprovado" , "Desistência do cliente", "Perdemos para concorrência")
##Jeito mais eficiente de fazer (testar eficiência, mas logicamente mais eficiente já que quebra em intervalos e depois substitui, ao invés de rodar toda a matrix)
ng_ij_hist_ij_ven_anat_ij_np_fec$negocio_status <- with(ng_ij_hist_ij_ven_anat_ij_np_fec, cut(negocio_negocio_situacao_id, breaks = c(0,4,5,6,7),
                                                                                              labels = status_4_5_6_7))

ng_ij_hist_ij_ven_anat_ij_np_fec <- ng_ij_hist_ij_ven_anat_ij_np_fec %>%
  filter (np_ativo == TRUE)

##agrupamento de negocios por vendedor, contando número de negócios por status e por vendedor
##Aqui eu poderia fazer um group_by + summarise pra ter apenas coluna id_vendedor + count(negocios) e depois o join, sem o select, ou então usar o mutate como foi feito
ng_ij_vn_ij_np_fech_fat <- ng_ij_hist_ij_ven_anat_ij_np_fec %>%
  select(negocio_id, negocio_vendedor_id, negocio_status, vendedor_nome, negocio_vendedor_id, np_valor) %>%
  group_by(negocio_status, negocio_vendedor_id) %>%
  mutate(total_fat = sum(np_valor)) %>%
  distinct (negocio_vendedor_id, .keep_all = TRUE) %>%
  collect ()

#usando função pra criar outra coluna com número formatado (em Real, com pontos)
ng_ij_vn_ij_np_fech_fat <- ng_ij_vn_ij_np_fech_fat %>%
  mutate(total_fat_t = func_fmt_din(total_fat))

### Gráfico n3 - Faturamento de negócios fechados em anat
#########################################################

n3 <- plot_ly(ng_ij_vn_ij_np_fech_fat, type = 'bar', orientation = 'h', x = ~total_fat , y = ~reorder(vendedor_nome, desc(vendedor_nome)),
              color = ~negocio_status,
              colors = c("#32CD32", "yellow", "orange", "#DE0D26"),
              name = ~negocio_status,
              showlegend = T
)

n3 <- n3 %>%
  layout(barmode = 'stack',
         xaxis = list(title = ''),
         yaxis = list(title = ''),
         legend = list(orientation = "h",
                       xanchor = "center"))

if(dash == F){
  n3
}

#########################################################

### Negócios por categoria
###########################################################################################################################################
###Aqui começa o gráfico de Tipos de máquina faturadas por categoria, em anat
#################################################
##Já utilizadas anteriormente
# negocio_produto <- fread("Tabelas/negocio_produto.csv") %>%
#   select(np_id, np_negocio_id, np_produto_id, np_quantidade,np_ativo, np_valor)

##Vou selecionar produto_nome pra não ter q mudar depois, mas posso cortar essa coluna se preciso e ir só por prod_id
# produto <- fread("Tabelas/produto.csv") %>%
#   select(produto_id, produto_nome, produto_marca_id, produto_categoria_id, produto_empresa_id)


## Inner join pra não pegar os np_produto_id = 0
ngp_ij_pd <- inner_join(negocio_produto, produto, by=c("np_produto_id"="produto_id"))%>%
  filter (np_ativo == TRUE) %>%
  select (np_negocio_id, np_produto_id, produto_nome, produto_marca_id, produto_categoria_id, produto_empresa_id, np_quantidade, np_valor)

if (teste == F) {
  rm()
}

##tabela usada pra termos negócios, data de atualização (hist), nome do vendedor (vend) e produtos (negocio produto e produto)
##Aqui temos já com alguns cortes (np_ativo)
ng_ij_hist_ij_ven_ij_ngp_ij_pd <- inner_join(ng_ij_hist_ij_ven_anat, ngp_ij_pd, by = c("negocio_id" = "np_negocio_id"))
## Removendo os inativos (np_ativo == 0)


##Vou fazer um join pra pegar os nomes de cada categoria
categoria <- fread("Tabelas/categoria.csv", colClasses = c(categoria_id = "character")) %>%
  select(categoria_id, categoria_nome)


Encoding(categoria$categoria_nome) <- 'latin1'


## Primeira vez pra verificar quais são os top10
ng_top10 <- ng_ij_hist_ij_ven_ij_ngp_ij_pd %>%
  select(produto_categoria_id, np_valor) %>%
  group_by(produto_categoria_id) %>%
  mutate(faturamento = sum(np_valor)) %>%
  distinct (produto_categoria_id, .keep_all = TRUE) %>%
  arrange(desc(faturamento)) %>%
  collect ()

##pega só os top10
top10 <- head.matrix(ng_top10, n=10)

top10_ij <- inner_join(top10, categoria, by = c("produto_categoria_id"="categoria_id"))
#Removendo a contagem que ele fez de faturamento (usado pra gerar o top10)
top10_ij <- top10_ij[, -2:-3]
top10_ij <- as.data.frame(top10_ij)

## Transformando tudo em "OUTRA" -1
ng_ij_hist_ij_ven_ij_ngp_ij_pd_ij_cat <- left_join(ng_ij_hist_ij_ven_ij_ngp_ij_pd, top10_ij, by=c("produto_categoria_id" = "produto_categoria_id"))
ng_ij_hist_ij_ven_ij_ngp_ij_pd_ij_cat$produto_categoria_id[is.na(ng_ij_hist_ij_ven_ij_ngp_ij_pd_ij_cat$categoria_nome)] <- "-1"
ng_ij_hist_ij_ven_ij_ngp_ij_pd_ij_cat$categoria_nome[is.na(ng_ij_hist_ij_ven_ij_ngp_ij_pd_ij_cat$categoria_nome)] <- "OUTRA"

## Removendo os NA (três negócios cadastrados errados)
ng_ij_hist_ij_ven_ij_ngp_ij_pd_ij_cat <- ng_ij_hist_ij_ven_ij_ngp_ij_pd_ij_cat[!is.na(ng_ij_hist_ij_ven_ij_ngp_ij_pd_ij_cat$np_produto_id),]


## Agora pra agrupar todos (já trocado os anteriores pra categoria "OUTRA")
ng_top10_ag <- ng_ij_hist_ij_ven_ij_ngp_ij_pd_ij_cat %>%
  select(produto_categoria_id, np_valor) %>%
  group_by(produto_categoria_id) %>%
  mutate(faturamento = sum(np_valor)) %>%
  distinct (produto_categoria_id, .keep_all = TRUE) %>%
  arrange(desc(faturamento)) %>%
  collect ()

##pega só os top10
top10 <- head.matrix(ng_top10_ag, n=10)


top10_ij <- inner_join(top10, categoria, by = c("produto_categoria_id"="categoria_id"))
#Removendo a contagem que ele fez de faturamento (usado pra gerar o top10)
top10_ij <- top10_ij[, -2]
top10_ij <- top10_ij[, -2]
top10_ij <- as.data.frame(top10_ij)

ng_top_ag <- inner_join(ng_top10_ag, top10_ij, by=c("produto_categoria_id" = "produto_categoria_id"))

#conversão de faturamento para texto
ng_top_ag <- ng_top_ag %>%
  mutate(fat_t = func_fmt_din(faturamento))

##Chart gerado para o treemap de categorias por faturamento em anat
chart_ng_top_ag <- ng_top_ag

### Gráfico hc_n4 - Valor financeiro de negócios em anat  (por categoria)
#################################################

hc_n4 <- chart_ng_top_ag %>%
  hchart (
    type = "treemap",
    hcaes(x=categoria_nome, value=faturamento, color = faturamento, name = categoria_nome)) %>%
  hc_tooltip(formatter = JS("function () { return '<b>' + this.point.categoria_nome + '</b><br /> ' + ' <br />' + this.point.fat_t;}")) %>%
  hc_colorAxis(minColor = "#ADD8E6", maxColor = "#3182FF")

if(dash == F){
  hc_n4
}

#################################################

### Aqui começa o gráfico de Tipos de máquina faturadas por categoria, em anat
#################################################


ng_ij_hist_ij_ven_ij_ngp_ij_pd_ij_cat_fat <-  ng_ij_hist_ij_ven_ij_ngp_ij_pd_ij_cat %>%
  filter(negocio_negocio_situacao_id == 4)

## Agora pra agrupar todos (já trocado os anteriores pra categoria "OUTRA")
ng_top10_ag_fat <- ng_ij_hist_ij_ven_ij_ngp_ij_pd_ij_cat_fat %>%
  select(produto_categoria_id, np_valor) %>%
  group_by(produto_categoria_id) %>%
  mutate(faturamento = sum(np_valor)) %>%
  distinct (produto_categoria_id, .keep_all = TRUE) %>%
  arrange(desc(faturamento)) %>%
  collect ()


ng_top_ag_fat <- inner_join(ng_top10_ag_fat, top10_ij, by=c("produto_categoria_id" = "produto_categoria_id"))
ng_top_ag_fat <- ng_top_ag_fat %>%
  select (produto_categoria_id, categoria_nome, faturamento)

#Removendo tabelas não mais usadas
if (teste == F) {
  #tabelas
  rm(ng_top10, ng_top10_ag, top10, top10_ij, ng_ij_hist_ij_ven_ij_ngp_ij_pd, ng_ij_hist_ij_ven_ij_ngp_ij_pd_ij_cat, ngp_ij_pd)
}

#conversão de faturamento para texto
ng_top_ag_fat <- ng_top_ag_fat %>%
  mutate(fat_t = func_fmt_din(faturamento))

##Chart gerado para o treemap de categorias por faturamento em anat
chart_ng_top_ag_fat <- ng_top_ag_fat

### Gráfico hc_n5 - Máquinas faturadas em anat (por categoria)
hc_n5 <- chart_ng_top_ag_fat %>%
  hchart (
    "treemap",
    hcaes(x=categoria_nome, value=faturamento, color = faturamento)) %>%
  hc_tooltip(formatter = JS("function () { return '<b>' + this.point.categoria_nome + '</b><br /> ' + ' <br />' + this.point.fat_t;}")) %>%
  hc_colorAxis(minColor = "#90EE90", maxColor = "#32CD32")

if(dash == F){
  hc_n5
}

if (teste == F) {
  rm(ng_top_ag, ng_top_ag_fat, ng_ij_hist_ij_ven_ij_ngp_ij_pd_ij_cat_fat, chart_ng_top_ag, chart_ng_top_ag_fat, ng_top10_ag_fat, ng_ij_hist_ij_ven_anat)
}
#################################################

### Idade dos negócios
###################################################################################################################################
##Filtrar vendedores ativos e empresa
ng_ij_hist_ij_ven_emp <- negocio_ij_historico_ij_vendedor_total %>%
  filter (vendedor_empresa_id == empresa)

##filtrando dois negócios que tem seu status 0 (possivel erro)
ng_ij_hist_ij_ven_emp <- ng_ij_hist_ij_ven_emp %>%
  filter(negocio_negocio_situacao_id != 0)

## Vou ordenar por historico_negocio_situacao_situacao_id pra depois remover as atualizações mais novas, ficar só com a primeira atualização após mudança de status
ng_ij_hist_ij_ven_emp_idd <- ng_ij_hist_ij_ven_emp[order(ng_ij_hist_ij_ven_emp$historico_negocio_situacao_situacao_id, ng_ij_hist_ij_ven_emp$negocio_id), ]

##Aqui estou removendo duplicatas (de outra forma), que removem apenas quando o histórico_situacao e negocio_id se repetem
ng_ij_hist_ij_ven_emp_idd <- subset(ng_ij_hist_ij_ven_emp_idd, !duplicated(subset(ng_ij_hist_ij_ven_emp_idd, select=c(negocio_id))))

##filtrando apenas negócios não fechados negocio_situacao_id != 4,5,6,7,9
ff = c(4,5,6,7,9)

ng_ij_hist_ij_ven_ab <- ng_ij_hist_ij_ven_emp_idd %>%
  filter(!negocio_negocio_situacao_id %in% ff)


status_aberto = c("1 - em negociacao", "2 - montagem de cadastro", "3 - aguardando aprovacao", "4 - financiamento aprovado", "0 - intencao ou prospeccao")
##Jeito mais eficiente de fazer (testar eficiência, mas logicamente mais eficiente já que quebra em intervalos e depois substitui, ao invés de rodar toda a matrix)
ng_ij_hist_ij_ven_ab$negocio_status <- with(ng_ij_hist_ij_ven_ab, cut(negocio_negocio_situacao_id, breaks = c(0,1,2,3,8,10),
                                                                      labels = status_aberto))

##filtrando dois negócios que tem seu status 0 (possivel erro)
ng_ij_hist_ij_ven_ab <- ng_ij_hist_ij_ven_ab %>%
  filter(negocio_negocio_situacao_id != 0)

idades = c("Até 2 meses", "De 2 a 6 meses", "De 6 a 12 meses", "De 12 a 24 meses", "Mais de 24 meses")

ng_ij_hist_ij_ven_idd <- ng_ij_hist_ij_ven_ab %>%
  select (negocio_id, negocio_vendedor_id, negocio_negocio_situacao_id, negocio_data_cadastro, vendedor_nome, historico_negocio_situacao_data) %>%
  mutate(idade = (as.integer(today() - as_date(negocio_data_cadastro)))) %>%
  mutate(idade_cat = NA) %>%
  arrange(idade)

ng_ij_hist_ij_ven_idd$idade_cat <- with(ng_ij_hist_ij_ven_idd, cut(idade, breaks = c(0,60, 180, 365, 730, 10000),
                                                                   label = idades))

##Aqui eu posso fazer um group_by + summarise pra ter apenas coluna id_vendedor + count(negocios c/status) e depois o join, sem o select, ou então usar o mutate como foi feito
ng_ij_hist_ij_ven_num <- ng_ij_hist_ij_ven_idd %>%
  select(negocio_id, negocio_vendedor_id, vendedor_nome, idade, idade_cat) %>%
  group_by(idade_cat, negocio_vendedor_id) %>%
  mutate(num_negocios_idades = n()) %>%
  distinct (idade_cat, .keep_all = TRUE) %>%
  collect ()

##Usado pra ordenar o gráfico
ng_ij_hist_ij_ven_num$idade_cat = factor(ng_ij_hist_ij_ven_num$idade_cat, levels = c("Até 2 meses", "De 2 a 6 meses", "De 6 a 12 meses", "De 12 a 24 meses", "Mais de 24 meses"))

n6 <- plot_ly(ng_ij_hist_ij_ven_num, type = 'bar', orientation = 'h', x=~num_negocios_idades , y=~reorder(vendedor_nome, desc(vendedor_nome)),
              color = ~idade_cat,
              colors = c("#32CD32", "#87CEFA" , "yellow" , "orange" , "#DE0D26"))
n6 <- n6 %>%
  layout(barmode = 'stack',
         xaxis = list(title = ''),
         yaxis = list(title = ''))
n6

if(dash == F){
  n6
}


if (teste == F) {
  #tabelas
  rm(ng_ij_hist_ij_ven_num, ng_ij_hist_ij_ven_ab)
  #variáveis
  rm(ff, idades, status_aberto)
}
###########################################



###Negócios abertos da empresa
############################################################################
ng_ij_hist_ij_emp_num <- ng_ij_hist_ij_ven_idd %>%
  select(idade, idade_cat) %>%
  group_by(idade_cat) %>%
  mutate(num_negocios_idades = n()) %>%
  distinct (idade_cat, .keep_all = TRUE) %>%
  collect ()

total_negocios = sum(ng_ij_hist_ij_emp_num$num_negocios_idades)

ng_ij_hist_ij_emp_num <- ng_ij_hist_ij_emp_num %>%
  select(idade, idade_cat, num_negocios_idades) %>%
  group_by(idade_cat) %>%
  mutate(porcentagem = num_negocios_idades/total_negocios) %>%
  mutate(porcent = scales::percent(porcentagem)) %>%
  distinct (idade_cat, .keep_all = TRUE) %>%
  arrange(idade) %>%
  collect ()

ng_ij_hist_ij_emp_num$idade_cat = factor(ng_ij_hist_ij_emp_num$idade_cat, levels = c("Até 2 meses", "De 2 a 6 meses", "De 6 a 12 meses", "De 12 a 24 meses", "Mais de 24 meses"))

### Gráfico n7 - Negócios abertos da empresa, pizza

colors_pie <- c("#32CD32", "#87CEFA" , "yellow" , "orange" , "#DE0D26")
n7 <- plot_ly(ng_ij_hist_ij_emp_num, labels = ~idade_cat, values = ~num_negocios_idades, type = 'pie', sort = F,
              texttemplate = "%{value} (%{percent})",
              hovertemplate = paste ("%{label} <br>",
                                     "Equivalente a %{percent}",
                                     "<extra></extra>"),
              marker = list(colors = colors_pie))

if(dash == F){
  n7
}

if (teste == F) {
  #tabelas
  rm(ng_ij_hist_ij_ven_idd, ng_ij_hist_ij_emp_num)
  #variáveis
  rm(colors_pie, total_negocios)
}
#######################################################################################################

### Funil de vendas (vendas abertas)
########################################################################
##Status aberto
st_a = c(1,2,3,8,10)
##vou tentar remover apenas os que tem status fechado (4 - faturado, 5 - financiamento não aprovado, 6 - desistência do cliente, 7 - perdemos para a concorrência)
##Tempo: Total
##status abertos apenas
ng_ij_hist_ij_ven_funil_ab <- neg_ij_ven_ij_np %>%
  filter(negocio_negocio_situacao_id %in% st_a)

##filtrar apenas por empresa
ng_ij_hist_ij_ven_funil_ab <- ng_ij_hist_ij_ven_funil_ab %>%
  filter(vendedor_empresa_id == empresa)

status = c("Em negociação", "Montagem de cadastro", "Aguardando aprovação", "Financiamento aprovado", "Intenção ou prospecção")
#Criando nova coluna para não perder o id status (ao mudar pra string)
ng_ij_hist_ij_ven_funil_ab <- ng_ij_hist_ij_ven_funil_ab %>%
  mutate(negocio_status = negocio_negocio_situacao_id)

##aqui ele substitui linha a linha cada situação pelo seu respectivo em string
ng_ij_hist_ij_ven_funil_ab$negocio_status <- with(ng_ij_hist_ij_ven_funil_ab, cut(negocio_negocio_situacao_id, breaks = c(0,1,2,3,8,10),
                                                                                  labels = status))

##Agora será agrupado por pedidos em aberto e faturamento total
ng_ij_hist_ij_ven_funil_fat <- ng_ij_hist_ij_ven_funil_ab %>%
  select (negocio_status, np_valor, negocio_negocio_situacao_id) %>%
  group_by(negocio_status) %>%
  mutate(total_faturado = sum(np_valor)) %>%
  arrange(negocio_status) %>%
  distinct(negocio_status, .keep_all = TRUE) %>%
  collect()



##conversão de faturamento para texto
ng_ij_hist_ij_ven_funil_fat <- ng_ij_hist_ij_ven_funil_fat %>%
  mutate(tot_fat_t = func_fmt_din(total_faturado))

##Começando a gambiarra (criar nova columa com nome da categoria + valor da categoria)
ng_ij_hist_ij_ven_funil_fat <- ng_ij_hist_ij_ven_funil_fat %>%
  mutate(nome_cat_valor_fat = paste(negocio_status, "\n", tot_fat_t))

##Vou converter o id de situação pra 0, pra poder ordenar (intenção seria o status 0, é o primeiro)
ng_ij_hist_ij_ven_funil_fat$negocio_negocio_situacao_id[ng_ij_hist_ij_ven_funil_fat$negocio_negocio_situacao_id == 10] <- 0
ng_ij_hist_ij_ven_funil_fat <- ng_ij_hist_ij_ven_funil_fat %>%
  arrange(negocio_negocio_situacao_id)

##Fechados do mês
##Status fechado
st_f = c(4,5,6,7)
status_f = c("Faturado", "Financiamento não aprovado", "Desistencia do cliente", "Perdemos para concorrência")

##vou tentar remover apenas os que tem status fechado (4 - faturado, 5 - financiamento não aprovado, 6 - desistência do cliente, 7 - perdemos para a concorrência)
##Tempo: Total
##status abertos
#ng_rj já havia feito o corte apenas em fechados após anat
ng_ij_hist_ij_ven_fec_anat <- ng_ij_hist_ij_ven_ij_np_anat %>%
  filter(negocio_negocio_situacao_id %in% st_f)

##Funil já filtrou (na verdade ng_ij_hist_ij_ven_anat já filtrou) vendedor ativo e empresa = 16

#Criando nova coluna para não perder o id status (ao mudar pra string)
ng_ij_hist_ij_ven_fec_anat <- ng_ij_hist_ij_ven_fec_anat %>%
  mutate(negocio_status = negocio_negocio_situacao_id)

##aqui ele substitui linha a linha cada situação pelo seu respectivo em string
ng_ij_hist_ij_ven_fec_anat$negocio_status <- with(ng_ij_hist_ij_ven_fec_anat, cut(negocio_negocio_situacao_id, breaks = c(0,4,5,6,7),
                                                                                  labels = status_f))

##Agora será agrupado por pedidos em aberto e faturamento total
ng_ij_hist_ij_ven_funil_fat_fec_anat <- ng_ij_hist_ij_ven_fec_anat %>%
  select (negocio_status, np_valor) %>%
  group_by(negocio_status) %>%
  mutate(total_faturado = sum(np_valor)) %>%
  arrange(negocio_status) %>%
  distinct(negocio_status, .keep_all = TRUE) %>%
  collect()


##############################################
##Criando nova tabela com dados apenas do mês anterior
##Auxiliares para meses
this_month <- today()
day(this_month) <- 1
last_month <- this_month-months(1)
ng_ij_hist_ij_ven_funil_fat_fec_anat_mes <- ng_ij_hist_ij_ven_fec_anat %>%
  filter(last_month <= historico_negocio_situacao_data,  historico_negocio_situacao_data < this_month) %>%
  mutate(negocio_status = negocio_negocio_situacao_id)

##aqui ele substitui linha a linha cada situação pelo seu respectivo em string
ng_ij_hist_ij_ven_funil_fat_fec_anat_mes$negocio_status <- with(ng_ij_hist_ij_ven_funil_fat_fec_anat_mes, cut(negocio_negocio_situacao_id, breaks = c(0,4,5,6,7),
                                                                                                              labels = status_f))

##Agora será agrupado por pedidos em aberto e faturamento total
ng_ij_hist_ij_ven_funil_fat_fec_anat_mes <- ng_ij_hist_ij_ven_funil_fat_fec_anat_mes %>%
  select (negocio_status, np_valor) %>%
  group_by(negocio_status) %>%
  mutate(total_faturado = sum(np_valor)) %>%
  arrange(negocio_status) %>%
  distinct(negocio_status, .keep_all = TRUE) %>%
  collect()


##Coluna nova criada para facilitar compreensão (diminui as casas para exibir em milhões)
ng_ij_hist_ij_ven_funil_fat_fec_anat_mes  <- ng_ij_hist_ij_ven_funil_fat_fec_anat_mes  %>%
  select (negocio_status, total_faturado) %>%
  mutate(tot_fat_m = as.integer(total_faturado/1000000))


#criando uma coluna nova para usar como texto dentro do gráfico
ng_ij_hist_ij_ven_funil_fat_fec_anat_mes <- ng_ij_hist_ij_ven_funil_fat_fec_anat_mes %>%
  mutate(total_fat_t = func_fmt_din_mi(total_faturado))

### Gráfico n11 - Pizza fechados no último mês
##############################################

colors_pie <- c("#32CD32", "yellow" , "orange" , "#DE0D26")
n11 <- plot_ly(ng_ij_hist_ij_ven_funil_fat_fec_anat_mes, labels = ~negocio_status, values = ~total_faturado, type = 'pie', sort = F,
               text = ~total_fat_t,
               texttemplate = "%{text}mi (%{percent})",
               hovertemplate = paste ("%{label} <br>",
                                      "%{text}mi <br>",
                                      "Equivalente a %{percent}",
                                      "<extra></extra>"),
               marker = list(colors = colors_pie))

if(dash == F){
  n11
}

if (teste == F){
  #tabelas
  rm(ng_ij_hist_ij_ven_funil_fat_fec_anat, ng_ij_hist_ij_ven_funil_fat_fec_anat_mes, ng_ij_hist_ij_ven_fec_anat)
  #variáveis
  rm(colors_pie, st_f, status_f, this_month, last_month)
}

##############################################
###Tempo médio de vida de um negócio

ng_cad_fin <- ng_ij_hist_ij_ven_emp %>%
  select (negocio_id, negocio_data_cadastro, negocio_negocio_situacao_id, historico_negocio_situacao_situacao_id, historico_negocio_situacao_data) %>%
  arrange (desc(historico_negocio_situacao_data), negocio_id)

##Aqui estou removendo duplicatas (de outra forma), que removem apenas quando negocio_id se repete
ng_cad_fin <- subset(ng_cad_fin, !duplicated(subset(ng_cad_fin, select=c(negocio_id))))

##Já estou filtrando apenas status fechados (faturado, financiamento não aprovado, desistência do cliente, perdemos para a concorrência)
ng_cad_fin <- ng_cad_fin %>%
  filter(negocio_negocio_situacao_id == 4 | negocio_negocio_situacao_id == 5 | negocio_negocio_situacao_id == 6 | negocio_negocio_situacao_id == 7) %>%
  mutate(temp_d = date(historico_negocio_situacao_data) - date(negocio_data_cadastro))

##Calculando tempo médio
ng_cad_fin <- ng_cad_fin %>%
  group_by(negocio_negocio_situacao_id) %>%
  mutate(media_d = round(mean(temp_d)), 2) %>%
  distinct(negocio_negocio_situacao_id, .keep_all = T) %>%
  ungroup() %>%
  select (negocio_negocio_situacao_id, media_d)


##Só pra ver os nomes
ng_cad_fin <- ng_cad_fin %>%
  mutate(Status = case_when(negocio_negocio_situacao_id == 4 ~ "Faturado",
                            negocio_negocio_situacao_id == 5 ~ "Financ. não aprovado",
                            negocio_negocio_situacao_id == 6 ~ "Desist. do cliente",
                            negocio_negocio_situacao_id == 7 ~ "Perdemos para conc."))

ng_cad_fin <- ng_cad_fin %>%
  mutate (media_d = paste(as.character(media_d),"dias")) %>%
  arrange(negocio_negocio_situacao_id)
valuebox <- data.frame(
  x = rep(seq(2, 9, 6.5), 2),
  y = c(rep(6.5, 2), rep(2,2)),
  h = rep(4.25, 4),
  w = rep(6.25, 4),
  value = ng_cad_fin$media_d,
  info = ng_cad_fin$Status,
  shape = c(fontawesome('fa-calendar'), fontawesome('fa-calendar'), fontawesome('fa-calendar'), fontawesome('fa-calendar')),
  font_family = c(rep("fontawesome-webfont", 4)),
  color = factor(1:4))
### Gráfico n13 - Tempo de vida médio de um negócio faturado (status = faturado)
colors <- c("#32CD32", "#FFD700" , "orange" , "#DE0D26")
n13 <- ggplot(valuebox, aes(x=x, y=y, height = h, width = w, label = info)) +
  geom_tile(aes(fill = color)) +
  geom_text(color = "white", fontface = "bold", size = 18,
            aes(label = value, x = x - 2.9, y = y + 1), hjust = 0) +
  geom_text(color = "white", fontface = "bold", size = 12,
            aes(label = info, x = x - 2.9, y = y - 1), hjust = 0) +
  coord_fixed() +
  scale_fill_manual(values = colors) +
  geom_text(size = 20, aes(label = shape, family = font_family,
                           x = x + 1.5, y = y + 0.5), alpha = 0.25) +
  theme_void() +
  guides(fill = FALSE)

if (dash == F){
  n13
}

### Gráfico n14 - Tempo de vida médio de um negócio perdido (status = desistência do cliente ou perdemos para concorrência)

if (dash == F){
  #n14
}

if (teste == F){
  #tabelas
  rm(ng_ij_hist_ij_ven_emp, valuebox, ng_cad_fin)
  #variáveis
  rm()
}

```

Faturamento de negócios
=======================================================================

Column {data-width=650}
-----------------------------------------------------------------------

### Faturamento dos negócios cadastrados por vendedor, ano 2020 (Status atual)

```{r}
### Gráfico n0 - Número de clientes por vendedor
n0 %>%
  layout(legend = list(orientation = "h", x = 0.5,
                       xanchor = "center"))

```

Column {data-width=350}
-----------------------------------------------------------------------

### Faturamento de negócios fechados em 2020

```{r}
### Gráfico n3 - Faturamento de negócios fechados em 2020
n3 %>%
  layout(legend = list(orientation = "h", x = 0.5,
                       xanchor = "center"))

```

Top 10 Categorias
=======================================================================

Column {data-width=350}
-----------------------------------------------------------------------
###  Valor Financeiro de Negócios Cadastrados, por categoria em 2020

```{r}
### Gráfico hc_n4 - Valor financeiro de negócios em 2020  (por categoria)
hc_n4

```

Column {data-width=350}
-----------------------------------------------------------------------
### Valor Financeiro de Negócios Faturados, por categoria em 2020

```{r}
### Gráfico hc_n5 - Máquinas faturadas em 2020 (por categoria)
hc_n5

```

Idade dos negócios
=======================================================================

Column {data-width=450}
-----------------------------------------------------------------------
### Idade dos negócios abertos, por vendedor
```{r}
### Gráfico n6 - Idade dos negócios abertos, por vendedor, por idade do negocio
n6
```


Column {data-width=350}
-----------------------------------------------------------------------
### Negócios abertos da empresa
```{r}
### Gráfico n7 - Negócios abertos da empresa, pizza
n7
```

### Tempo médio para fechamento dos negócios (por status)
```{r}
### Gráfico n13 - Tempo de vida médio de um negócio faturado (status = faturado)
n13
```